### ISSUE TITLE
Pyramidal TIFF Support

### ISSUE THREAD

**Issue by tmgodinho** [geosolutions-it/imageio-ext#109]
Is there anyway to write image pyramids with the tiff writer?

Thanks

**Comment by haraldk** [comment]
@tmgodinho I believe any TIFF writer that can write multiple image TIFFs, can also create "pyramidal TIFFs". It's just a matter of providing input images at the correct resolution (successively halving the resolution for each step).

**Comment by tmgodinho** [comment]
Thanks this has been helpful :)
