### ISSUE TITLE
PNGJ encoder fails to encode gray/alpha images resulting from a band selection

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/imageio-ext#116]
Take a 4 bands image, e.g., RGBA, select R and A using a band select, the BandSelect won't actually create new rasters, but will leave the data and create a sample model with band offsets (3,0).
The current RasterByteGrayAlphaProvider considers the (1,0) and (0,1) cases, but does not work when the underlying raster has more than 2 bands stored, and just has to pick the gray and alpha ones from it.

**Comment by dromagnoli** [comment]
The same will happen when encoding RGB from BandSelect performed on RGBA image.
