### ISSUE TITLE
where to download binary jar releases

### ISSUE THREAD

**Issue by edeso** [geosolutions-it/imageio-ext#144]
hi,

the readme states that downloads are available here
  http://demo.geo-solutions.it/share/github/imageio-ext/releases/1.1.X/

the github releases section does only contain source files
  https://github.com/geosolutions-it/imageio-ext/releases

but the folders since 1.17 are empty. where can i get the latest 1.19 release.

thanks.. ede

**Comment by dromagnoli** [comment]
Fixed. 
deployment script has been updated.
